### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by Sahib7777** [omurad/dotapicker-autopicker#1]
How do i use this? whenever i run the .py file it just opens a cmd window and closes

**Comment by omurad** [comment]
The purpose of this project was to make a better, less buggy version of the Overwolf autopicker client with more features. But since I began working on this another project has popped up that is 100x better than Overworlf/DotaPicker.com and its called [Stratz+](https://stratz.com/plus).

So since Stratz+ is so much better (machine learning vs. statistics, smurf detection, accounts for player history, etc....) I stopped working on this project. I'll probably be deleting this repo soon.

**Comment by Sahib7777** [comment]
Hey omar thank you could you help me out with stratz plus downloaded it using it but issues like full screen mode need your help any discord link? 

Sent from Yahoo Mail on Android 
 
  On Tue, 5 May 2020 at 20:32, Omar<notifications@github.com> wrote:   


The purpose of this project was to make a better, less buggy version of the Overwolf autopicker client with more features. But since I began working on this another project has popped up that is 100x better than Overworlf/DotaPicker.com and its called Stratz+.

So since Stratz+ is so much better (machine learning vs. statistics, smurf detection, accounts for player history, etc....) I stopped working on this project. I'll probably be deleting this repo soon.

**Comment by omurad** [comment]
Stratz+ has their own discord at the bottom of their website where you can ask for help.

It should be as easy as launching the Stratz+ client then launching Dota 2.

**Comment by Sahib7777** [comment]
Yes has a bug unable to use it sadly vedio resolution error for borderless window i joined their discord thanks omar 

Sent from Yahoo Mail on Android 
 
  On Wed, 6 May 2020 at 21:47, Omar<notifications@github.com> wrote:   


Stratz+ has their own discord at the bottom of their website where you can ask for help.

It should be as easy as launching the Stratz+ client then launching Dota 2.
